multiplicacion de dos matrices


In [3]:
a=(1,2),(3,4),(4,5),(6,1)

In [6]:
type(a)

tuple

In [24]:
a_f=int(input("Ingrese el numero de filas"))

Ingrese el numero de filas 4


In [25]:
len(a_)

4

In [4]:
len(a[0])

2

In [20]:
a

((1, 2), (3, 4), (4, 5), (6, 1))

In [9]:
b= ([1,2,3],[1,2,3])

In [10]:
type(b)

tuple

In [11]:
import numpy as np

In [15]:
a_=np.asarray(a)

In [17]:
b_=np.asarray(b)

In [16]:
type(a_)

numpy.ndarray

In [18]:
b_

array([[1, 2, 3],
       [1, 2, 3]])

In [19]:
b

([1, 2, 3], [1, 2, 3])

In [21]:
a_


array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 1]])

In [22]:
b_

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
for i in range(4);
for j in range(2);